
# FROM intarna_docker
# https://quay.io/repository/biocontainers/intarna
FROM quay.io/biocontainers/intarna:3.3.2--pl5321h7ff8a90_0
# FROM quay.io/biocontainers/intarna:3.0.0--pl526h78a066a_0
# FROM quay.io/prometheus/node-exporter
# FROM quay.io/jetstack/cert-manager-controller:v1.10.0

# ARG NODE_VERSION="none"
# RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

################################################################################
#  Install python dependencies
################################################################################

################################################################################
#  setup environment
################################################################################

# ENTRYPOINT ["/bin/bash"]